name: Dependency scan

on:
  workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              
            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                go-version: 1.22
                go-version-file: 
                
            - name: Install Govulncheck
              run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

            - name: Go vulncheck
              run: govulncheck ./...
              working-directory: backend
              
            - name: upload Reports to artificats
              uses: actions/upload-artifact@v4
              with:
                 name: job-report
                 path: reports/junit-report.txt
                 retantion-days: 5

            - name: Setup Node Js
              uses: actions/setup-node@v6
              with:
                node-version: '20'
                cache: npm
                cache-dependency-path: frontend/package-lock.json
                
            - name: Run Dependency scan for node
              run: npm audit
              working-directory: frontend
            

              
              
