# Goal - To Run End to End DevSecOps CI Pipeline

name: DevSecOps

on:
    push:
        branches: [devsecops]

jobs:

    ## ---- CI ----
    # Code Stage 
    code-quality:
        uses: ./.github/workflows/code-quality.yaml

    # Secret Scanning
    secret-scanning:
        uses: ./.github/workflows/secert-scanning.yaml

    # Dependency Checks
    dependency-checks:
        uses: ./.github/workflows/dependency-scan.yaml

    # Docker Checks
    docker-checks:
        uses: ./.github/workflows/docker-scans.yaml
        secrets: inherit 

    # SonarQube
    sonar-qube:
        uses: ./.github/workflows/sonar-scan.yaml
        secrets: inherit

    # Code Tests
    code-tests:
        uses: ./.github/workflows/code-tests.yml

    # push-to-docker-hub:
    docker-push:
        uses: ./.github/workflows/docker-push.yml
        needs: [code-quality,code-tests,sonar-qube,docker-checks,dependency-checks,secret-scanning]
        secrets: inherit

    ## ---- CD -----
    deploy:
        needs: [docker-push]
        uses: ./.github/workflows/deploy.yml
        secrets: inherit

    









