name: devsecops

on:
    push:
        branches: [devsecops]
jobs:
    code-quality:
          uses: ./.github/workflows/code-quality.yaml
    secret-scanning:
           uses: ./.github/workflows/secert-scanning.yaml
    dependency-scanning:
        uses: ./.github/workflows/dependency-scan.yaml
    docker-scan:
       uses: ./.github/workflows/docker-scan.yaml
       
        
           
          
