name: Docker Scan

on:
  workflow_call:

jobs:
    docker-file-lint:
      runs-on: ubuntu-latest
      strategy:
           fall-fast:
           matrix:
               folders: ['backend','frontend']
      steps:
         - name: code Checkout
           uses: actions/checkout@v7
           
         - name: Dockerfile Lint
           uses: hadolint/hadolint-action@v3.1.0
           with:
              dockerfile: ${{ matrix.folders }}/Dockerfile
              
         - name: Docker Setup [login]
           uses: docker/login-action@v4
           with:
             username: ${{ vars.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKHUB_TOKEN }}
             
         - name: Docker Build ${{ matrix.folders}}
           run: docker buiuld -t ${{ vars.DOCKEHUB_USERNAME }}/devboard-${{ matrix.folders }}:latest . 
           working-directory: ${{matrix.folders}}
           
         - name: Run Trivy vulnerability scanner in fs mode
           uses: aquasecurity/trivy-action@v0.36.0
           with: 
             image-ref: ${{ vars.DOCKERHUB_USERNAME}}/devboard-${{ matrix.folders }}:latest .
             format: 'table'
             exit-code: '1'
             ignore-unfixed: true
             vuln-type: 'os,library'
             severity: 'CRITICAL,HIGH'


           
           
           

               
               
           
           
           
