#What is goal of workflow 
#Check syntax and formate are all good 

name: Auto Linter

on:
  push:
    paths:
      - "*.py"

jobs:
  code:
    runs-on: ubuntu-latest
    steps:
    #This step will automtically clone the current branch into runner
      - name: Checkout the code
        uses: actions/checkout@v7
        with:
          python-version: '3:14'
        
    #Setup python 
        
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
      
        
    #This step install linting tools
      - name: Install Linter
        run: pip install ruff
        
     #This step will run linter
      - name: Check files for linting
        run: ruff check . 
 
   
