name: Go Linter
on: 
  workflow_dispatch:
jobs:
   code-format:
      runs-on: ubuntu-latest
      strategy:
         fail-fast: false
         matrix:
            go-version: [1.19, 1.20, 1.21]
    
      steps:
         - name: code Checkout
           uses: action/checkout@v7 
         - name: setup go
           uses: actions/setup-go@v6
           with:
               go-version: ${{ matrix.go-version }}
               go-version-file: 'go.mod'
               cache-depdency-path: go.sum

         - name: Run go Formatter
           run: go fmt
           working-directory: backend

         - name: Run go vet
           run: go vet
           working-directory: backend
